### ISSUE TITLE
Typo for Sitecore on readme.md file

### ISSUE THREAD

**Issue by JuliusAngwenyi** [epam/sitecore-headless-commerce-accelerator#255]
- There is Sitecore typo on readme.md at https://github.com/epam/sitecore-headless-commerce-accelerator#known-issues-of-the-sitecre-commerce-server-installation

- There is a typo on readme.md at https://github.com/epam/sitecore-headless-commerce-accelerator#building--deploying-headless-commerce-accelerator bullet 6

**Comment by larionovadaria** [comment]
@JuliusAngwenyi  fixed 👍
