### ISSUE TITLE
Problem Loading Site in Experience Editor

### ISSUE THREAD

**Issue by tmamedbekov** [epam/sitecore-headless-commerce-accelerator#5]
I am running into the issue of loading the site in Experience Editor. 
Everything builds and deploys without any problems.

![image](https://user-images.githubusercontent.com/21371923/65971189-6b843b00-e42d-11e9-9ac2-d9e8b1ed61d2.png)

**Comment by ashishagin** [comment]
Hi Tony,

Thx for pointing to theissue. We were able to reproduce it. Taking in work.

Alexey

**Comment by ashishagin** [comment]
Fixed in #8
